config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    get :first, on: :collection
  end

  devise_for :users, skip: [:registrations]


  # Área de administración protegida
  namespace :admin do
    resources :products do  # CRUD de productos
        patch :change_stock, on: :member
        resources :product_variants, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :users do
      member do
        patch :deactivate
      end
    end

    resources :sales do  # Gestión de ventas
      patch :cancel, on: :member
    end
    
    root 'dashboard#index'  # Página principal del admin
  end

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
    # Storefront público
    root 'storefront#home'  # Página principal

    get "storefront", to: "storefront#home", as: :storefront_home
    get "storefront/:id", to: "storefront#show", as: :storefront_product
    resources :products, only: [:index, :show]  # Ver productos sin registro
end

app/models/product.rb
class Product < ApplicationRecord
    scope :active, -> { where(deactivated_at: nil) }

    has_many :product_variants, dependent: :destroy
    accepts_nested_attributes_for :product_variants, allow_destroy: true

    belongs_to :category

    has_one_attached :image

    # Atributo virtual para el checkbox
    attr_accessor :remove_image

    # Callback para eliminar la imagen si el checkbox está marcado
    before_save :purge_image_if_requested

    def stock
        product_variants.active.sum(:stock)
    end

  def deactivate!
    transaction do
      product_variants.update_all(deactivated_at: Time.current) # Desactiva todas las variantes
      update!(deactivated_at: Time.current)
    end
  end

    private

    def purge_image_if_requested
        puts "Remove Image: #{remove_image}" # Verifica el valor
        image.purge if ActiveModel::Type::Boolean.new.cast(remove_image)
    end
    
    validates :name, presence: true, length: { minimum: 7, maximum:30 }
    validates :description, presence: true, length: { minimum: 12, maximum:220 }
    validates :price, presence:true, numericality: { greater_than_or_equal_to: 0 }

    def active?
        deactivated_at.nil?
    end
      
    def self.ransackable_attributes(auth_object = nil)
        ["category", "color", "created_at", "deactivated_at", "description", "id", "name", "price", "size", "stock", "updated_at"]
    end
  
    def self.ransackable_associations(auth_object = nil)
      []
    end
    
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::DashboardController
  load_and_authorize_resource
  before_action :set_product, only: [:edit, :update, :destroy]

  #def index
  # @products = Product.active
  #end

  def index
    # Solo obtenemos los productos activos
    @q = Product.active.ransack(params[:q])
    # Aplicamos paginación al resultado de Ransack
    @products = @q.result(distinct: true).paginate(page: params[:page], per_page: 16)
  end

  def show
  end

  def new
    @product = Product.new
    @product.product_variants.build # Inicializa una variante vacía
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_products_path, notice: "Producto creado exitosamente."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    if @product.update(product_params)
      redirect_to admin_products_path, notice: "Producto actualizado exitosamente."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  #def destroy
  #  @product.update(deactivated_at: Time.current)
  #  redirect_to admin_products_path, notice: "Producto eliminado exitosamente."
  #end

  def destroy
    if @product.deactivate!
      redirect_to admin_products_path, notice: "Producto eliminado exitosamente."
    else
      redirect_to admin_products_path, alert: "No se pudo eliminar el producto."
    end
  end


  private

  def set_product
    @product = Product.find(params[:id])
  end


  private
  def product_params
    params.require(:product).permit(:name, :price, :description, :category_id, :color, :size, :image, :remove_image, product_variants_attributes: [:id, :size, :color, :stock, :_destroy])
  end

end

app/views/admin/products/_form.html.erb
<div class="flex items-center justify-center">
  <div class="<%= product.persisted? ? 'grid grid-cols-1 md:grid-cols-2 gap-6' : 'flex justify-center' %> w-full max-w-6xl">
    
    <!-- Formulario del producto -->
    <div class="<%= product.persisted? ? 'md:w-full' : 'w-full md:w-1/2' %> min-w-[300px]">
      <%= form_with model: product, url: [:admin, product], local: true, class: "p-8 shadow-2xl border rounded-lg bg-white h-full" do |form| %>
        <h1 class="text-2xl font-bold m-3 text-gray-800"><%= product.persisted? ? 'Editar' : 'Nuevo' %> modelo</h1>

        <!-- Campo Imagen -->
        <div class="relative w-full h-72 border border-gray-300 rounded-md bg-gray-100 overflow-hidden mt-5">
          <% if product.image.attached? && product.persisted? %>
            <%= image_tag product.image, class: "absolute inset-0 w-full h-full object-cover" %>
            <div class="absolute bottom-0 left-0 w-full bg-black bg-opacity-50 text-white flex justify-between items-center p-2 z-20">
              <span class="text-sm">Imagen actual</span>
              <button type="button" class="cursor-pointer text-sm font-bold hover:underline" onclick="document.getElementById('remove-image').click()">Eliminar</button>
              <%= form.check_box :remove_image, id: "remove-image", class: "hidden" %>
            </div>
          <% else %>
            <span class="absolute inset-0 flex items-center justify-center text-gray-500">No image available</span>
          <% end %>
          <label class="absolute inset-0 w-full h-full bg-transparent cursor-pointer flex items-center justify-center hover:bg-blue-300 hover:bg-opacity-50 z-10">
            <%= form.file_field :image, class: "hidden" %>
          </label>
        </div>

        <!-- Campos del formulario -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
          <div>
            <%= form.label :name, "Nombre", class: "block text-lg font-semibold mb-2" %>
            <%= form.text_field :name, required: true, minlength: 7, maxlength: 30, class: "w-full px-4 py-2 border rounded-md focus:ring-2 focus:ring-blue-400" %>
          </div>
          <div>
            <%= form.label :category_id, "Categoría", class: "block text-lg font-semibold mb-2" %>
            <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Seleccionar" }, required: true, class: "w-full px-4 py-2 border rounded-md focus:ring-2 focus:ring-blue-400" %>
          </div>
          <div>
            <%= form.label :description, "Descripción", class: "block text-lg font-semibold mb-2" %>
            <%= form.text_area :description, required: true, minlength: 12, maxlength: 220, class: "w-full px-4 py-2 border rounded-md focus:ring-2 focus:ring-blue-400" %>
          </div>
          <div>
            <%= form.label :price, "Precio", class: "block text-lg font-semibold mb-2" %>
            <%= form.number_field :price, step: 0.01, required:true, class: "w-full px-4 py-2 border rounded-md focus:ring-2 focus:ring-blue-400" %>
          </div>
        </div>
        <% if product.errors.any? %>
          <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-4">
            <p><strong>Se encontraron los siguientes errores:</strong></p>
            <ul>
              <% product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="mt-20 text-center">
          <%= form.submit "Guardar", class: " bg-blue-500 hover:bg-blue-600 cursor-pointer text-white font-bold py-2 px-4 rounded-lg shadow-md" %>
        </div>
      <% end %>
    </div>

    <% if product.persisted? %>
      <!-- Lista de variantes -->
      <div class="flex flex-col justify-between md:w-full min-w-[300px] border rounded-lg shadow-2xl bg-stone-100">
        <h2 class="text-2xl pt-7 text-center ">Editar variantes</h2>
        <!-- Contenedor de variantes con scroll interno -->
          <div class="flex flex-col justify-start overflow-y-auto px-3 max-h-[63vh] my-6">
            <% product.product_variants.active.each do |variant| %>
              <div class="flex items-center justify-between border-b pb-2 rounded-lg border-y-2 pt-2 mb-2 border-x-2 pl-4 bg-white">
                <div class='truncate'>
                  <p class='truncate'><strong>Talle:</strong> <%= variant.size %></p>
                  <p class='truncate'><strong>Color:</strong> <%= variant.color %></p>
                  <p class='truncate'><strong>Stock:</strong> <%= variant.stock %></p>
                </div>
                <div class="flex space-x-2 ml-2 p-4 border-l-2">
                  <%= link_to "Editar", edit_admin_product_product_variant_path(product, variant), class: "text-blue-500 hover:underline" %>
                  <%= button_to "Eliminar", admin_product_product_variant_path(product_id: product.id, id: variant.id), method: :delete, data: { turbo_confirm: "¿Estás seguro de eliminar esta variante?" }, class: "text-red-500 hover:underline" %>
                </div>
              </div>
            <% end %>
          </div>
        <%= link_to "Agregar variante", new_admin_product_product_variant_path(product), class: "rounded-lg text-center text-green-700 bg-green-100 font-bold hover:bg-green-200 px-4 py-2" %>
      </div>
    <% end %>

  </div>
</div>

app/views/admin/products/edit.html.erb
<% content_for :title, "Editar producto" %>
<%= render "form", product: @product %>  

app/views/admin/products/index.html.erb
<% content_for :title, "Ver productos" %>

<h1 class="text-3xl font-bold mb-6">Modelos</h1>

<%= search_form_for @q, url: admin_products_path, method: :get, class: "mb-6" do |f| %>
  <%= f.label :name_cont, "Buscar modelo por nombre:", class: "block font-semibold mb-2" %>
  <div class='flex h-16'>
  <%= f.text_field :name_cont, class: "border rounded mr-4 py-2 w-2/4 mb-4" %>
  <%= f.submit "Buscar", class: "bg-blue-600 hover:bg-blue-500 text-white h-12 py-2 px-4 rounded" %>
  </div>
<% end %>

<%= link_to "Agregar modelo", new_admin_product_path, class: "bg-green-600 hover:bg-green-500 text-white py-2 px-4 rounded"%>

<div id="products" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 my-10">
  <% @products.each do |product| %>
    <%= render 'shared/product', product: product, admin: true %>
  <% end %>
</div>

<div class="pagination">
  <%= will_paginate @products %>
</div>

app/views/admin/products/new.html.erb
<% content_for :title, "Agregar producto" %>
<%= render "form", product: @product %>