config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    get :first, on: :collection
  end

  devise_for :users, skip: [:registrations]


  # Área de administración protegida
  namespace :admin do
    resources :products do  # CRUD de productos
        patch :change_stock, on: :member
        resources :product_variants, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :users do
      member do
        patch :deactivate
      end
    end

    resources :sales do  # Gestión de ventas
      patch :cancel, on: :member
    end
    
    root 'dashboard#index'  # Página principal del admin
  end

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
    # Storefront público
    root 'storefront#home'  # Página principal

    get "storefront", to: "storefront#home", as: :storefront_home
    get "storefront/:id", to: "storefront#show", as: :storefront_product
    resources :products, only: [:index, :show]  # Ver productos sin registro
end

app/models/user.rb
class User < ApplicationRecord
  # Scope para usuarios activos
  scope :active, -> { where(deactivated_at: nil) }

  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #(por algún motivo los enum me tiran error...)
  #enum role: { admin: "admin", manager: "manager", employee: "employee" }

  # Validación
  #validates :role, presence: true

  ROLES = %w[admin manager employee].freeze

  validates :password, presence: true, if: :password_required?
  validates :username, presence: true, length: {minimum: 6, maximum: 20}, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :phone, length: {minimum: 8, maximum: 15}, presence: true
  validates :role, presence: true, inclusion: { in: ROLES }

  def admin?
    role == "admin"
  end

  def manager?
    role == "manager"
  end

  def employee?
    role == "employee"
  end
  
  def deactivate!
    update(deactivated_at: Time.current, password: SecureRandom.hex)
  end

  def active?
    deactivated_at.nil?
  end
  
  def password_required?
    # La contraseña es requerida si:
    # - Es un nuevo registro (new_record?)
    # - O el campo de password está presente (para cambios de contraseña)
    new_record? || password.present?
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::DashboardController
  load_and_authorize_resource
  before_action :set_user, only: [:edit, :update, :deactivate]

  def index
    @users = User.all
  end

  def new 
    @user = User.new
  end

  def create
    # Verificar si un gerente intenta asignar el rol admin
    if current_user.manager? && params[:user][:role] == 'admin'
      raise CanCan::AccessDenied.new
    end
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "Usuario creado exitosamente."
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
  
    # Si `role` no está en los params (cuando edito mi propio usuario), lo forzamos a su valor actual para que no esté vacío y no validemos sobre un campo que no llega desde el form lo cual causa problemas.
    params[:user][:role] = @user.role unless params[:user].key?(:role)
  
    # Verificar si un manager intenta asignar `admin`
    if current_user.manager? && params[:user][:role] == 'admin'
      raise CanCan::AccessDenied.new
    end
  
    # Verificar si el usuario está intentando cambiar su propio rol
    if current_user == @user && params[:user][:role] != @user.role
      raise CanCan::AccessDenied.new
    end
  
    if @user.update(user_params)
      if request.referer&.include?(edit_admin_user_path(current_user))
        redirect_to admin_root_path, notice: "Tu perfil se ha actualizado correctamente."
      else
        redirect_to admin_users_path, notice: "Usuario actualizado exitosamente."
      end
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :edit, status: :unprocessable_entity
    end
  end
  

  def deactivate
    @user.deactivate!
    redirect_to admin_users_path, notice: "Usuario desactivado exitosamente."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    permitted = [:username, :email, :phone, :password, :password_confirmation]
  
    if can?(:update, @user) && current_user != @user
      if current_user.manager?
        # Los gerentes pueden editar usuarios, pero no asignar el rol "admin"
        permitted << :role unless params[:user][:role] == 'admin'
      else
        # Los administradores pueden cambiar cualquier rol
        permitted << :role
      end
    end
  
    params.require(:user).permit(permitted)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admin/users/_form.html.erb
<%= form_with model: user, url: user.new_record? ? admin_users_path : admin_user_path(user), local: true, class: "max-w-lg mx-auto bg-white p-6 rounded-lg shadow-md space-y-4 mt-10", data: { controller: "user-form", action: "submit->user-form#validateForm" } do |f| %>
  
  <h1 class="text-3xl font-bold mb-3 text-gray-800"><%= user.persisted? ? 'Editar' : 'Crear' %> usuario</h1>

  <div>
    <%= f.label :username, "Nombre de usuario", class: "block font-medium text-gray-700 mb-1" %>
    <%= f.text_field :username, class: "w-full px-3 py-2 border rounded-lg shadow-sm focus:ring focus:ring-blue-300", required: true, data: { user_form_target: "username", action: "input->user-form#checkUsername" } %>
    <span data-user-form-target="usernameFeedback" class="text-sm"></span>
  </div>

  <div>
    <%= f.label :email, "Correo electrónico", class: "block font-medium text-gray-700 mb-1" %>
    <%= f.email_field :email, class: "w-full px-3 py-2 border rounded-lg shadow-sm focus:ring focus:ring-blue-300", required: true, data: { user_form_target: "email", action: "input->user-form#checkEmail" } %>
    <span data-user-form-target="emailFeedback" class="text-sm"></span>
  </div>

  <div>
    <%= f.label :phone, "Teléfono", class: "block font-medium text-gray-700 mb-1" %>
    <%= f.telephone_field :phone, class: "w-full px-3 py-2 border rounded-lg shadow-sm focus:ring focus:ring-blue-300", required: true, data: { user_form_target: "phone", action: "input->user-form#validatePhone" } %>
    <span data-user-form-target="phoneFeedback" class="text-sm"></span>
  </div>

  <% if current_user != user %>
    <div>
      <%= f.label :role, "Rol", class: "block font-medium text-gray-700 mb-1" %>
      <%= f.select :role, User::ROLES, {}, class: "w-full px-3 py-2 border rounded-lg shadow-sm focus:ring focus:ring-blue-300", required: true %>
    </div>
  <% end %>

  <div>
    <%= f.label :password, "Contraseña", class: "block font-medium text-gray-700 mb-1" %>
    <%= f.password_field :password, class: "w-full px-3 py-2 border rounded-lg shadow-sm focus:ring focus:ring-blue-300", autocomplete: "new-password", required: false, data: { user_form_target: "password", action: "input->user-form#validatePassword" } %>
    <span data-user-form-target="passFeedback" class="text-sm"></span>
  </div>

  <div>
    <%= f.label :password_confirmation, "Confirmar contraseña", class: "block font-medium text-gray-700 mb-1" %>
    <%= f.password_field :password_confirmation, class: "w-full px-3 py-2 border rounded-lg shadow-sm focus:ring focus:ring-blue-300", autocomplete: "new-password", required: false, data: { user_form_target: "passwordConfirmation", action: "input->user-form#validatePasswordConfirmation" } %>
    <span data-user-form-target="repassFeedback" class="text-sm"></span>
  </div>

  <div class="flex justify-end">
    <%= f.submit "Guardar", class: "bg-blue-500 hover:bg-blue-600 text-white font-medium px-4 py-2 rounded-lg shadow-md transition", data: { user_form_target: "submit" } %>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<% content_for :title, "Editar usuario" %>

<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", user: @user %>

</div>

app/views/admin/users/index.html.erb
<% content_for :title, "Ver usuarios" %>

<div class="max-w-5xl mx-auto p-6 bg-white shadow-md rounded-lg">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-bold text-gray-800">Gestión de Usuarios</h1>
    <%= link_to "Nuevo Usuario", new_admin_user_path, 
          class: "bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg shadow-md transition" %>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full bg-white border border-gray-300 shadow-sm rounded-lg">
      <thead class="bg-gray-100 text-gray-700">
        <tr>
          <th class="px-4 py-2 border">Nombre de Usuario</th>
          <th class="px-4 py-2 border">Correo</th>
          <th class="px-4 py-2 border">Teléfono</th>
          <th class="px-4 py-2 border">Rol</th>
          <th class="px-4 py-2 border">Estado</th>
          <th class="px-4 py-2 border">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr class="<%= user.active? ? 'bg-green-50 hover:bg-green-100' : 'bg-red-50 hover:bg-red-100' %>  transition">
            <td class="px-4 py-2 border text-center"><%= user.username %></td>
            <td class="px-4 py-2 border text-center"><%= user.email %></td>
            <td class="px-4 py-2 border text-center"><%= user.phone %></td>
            <td class="px-4 py-2 border text-center"><%= user.role.capitalize %></td>
            <td class="px-4 py-2 border text-center">
              <span class="px-2 py-1 rounded-full text-white text-sm font-semibold <%= user.active? ? 'bg-green-500' : 'bg-red-500' %>">
                <%= user.active? ? "Activo" : "Desactivado" %>
              </span>
            </td>
            <td class="px-4 py-2 border text-center space-x-2">
              <% if can?(:update, user) %>
                <%= link_to "Editar", edit_admin_user_path(user), 
                      class: "text-blue-500 hover:text-blue-700 font-semibold transition" %>
              <% end %>
              <% if can?(:deactivate, user) && user.active? %>
                <%= button_to "Desactivar", deactivate_admin_user_path(user),
                      method: :patch, 
                      data:  { turbo_confirm: "¿Estás seguro de que deseas desactivar este usuario?" }, 
                      class: "text-red-500 hover:text-red-700 font-semibold transition" %>
              <%end%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<% content_for :title, "Agregar usuario" %>

<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", user: @user %>

</div>